name: first-test

on: [pull_request, push]

jobs:
  fetch-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Clone OpenCV
        uses: actions/checkout@v3
        with:
          repository: opencv/opencv
      - name: Clone OpenCV contrib
        uses: actions/checkout@v3
        with:
          repository: opencv/opencv_contrib