name: first-test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone OpenCV repository
        uses: actions/checkout@v3
        with:
          repository: opencv/opencv